<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    xmlns:r="http://elpri.di.uminho.pt/report"
    xmlns:p="http://elpri.di.uminho.pt/paragraph"
    exclude-result-prefixes="xs xd"
    version="1.0">
    <xd:doc scope="stylesheet">
        <xd:desc>
            <xd:p><xd:b>Created on:</xd:b> Dec 15, 2014</xd:p>
            <xd:p><xd:b>Author:</xd:b> jcr</xd:p>
            <xd:p></xd:p>
        </xd:desc>
    </xd:doc>
    
    <xsl:output method="html" indent="yes"/>
    <xsl:template match="/">
        <html>
            <head>
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
                <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
                <title>Relatório</title>
            </head>
            <body>
                <xsl:apply-templates select="//front-matter"/>
                <address>Generated by </address>
                <hr/>
            </body>
        </html>
    </xsl:template>
    
    <xsl:template match="front-matter">
        <div class="col-xs-12">
            <xsl:apply-templates select="meta"/>
        </div>
    </xsl:template>
            
    <xsl:template match="meta">
        <div class="col-xs-10">
            <xsl:value-of select="."/>
        </div>
    </xsl:template>
        
    <xsl:template match="//body">
        <div class="col-xs-12">
            <xsl:apply-templates/>
        </div>
    </xsl:template>
        
    <xsl:template match="//back-matter">
        <div class="col-xs-12">
            <xsl:apply-templates/>
        </div>
    </xsl:template>
    
    <xsl:template match="text()" priority="-1"/>
    
</xsl:stylesheet>